### ISSUE TITLE
how to update with hi3798mv310

### ISSUE THREAD

**Issue by museany** [leandrotsampa/hisilicon-kernel#1]
i have a tvbox  ：haw to work it with linux system ?

HG680-KA-海思hi3798MV300芯片

getprop 

[bt.qcom6174.power]: [false]
[dalvik.vm.heapgrowthlimit]: [192m]
[dalvik.vm.heapmaxfree]: [32m]
[dalvik.vm.heapminfree]: [512k]
[dalvik.vm.heapsize]: [256m]
[dalvik.vm.heapstartsize]: [5m]
[dalvik.vm.heaptargetutilization]: [0.5]
[dalvik.vm.stack-trace-file]: [/data/anr/traces.txt]
[debug.force_rtl]: [0]
[debug.hwui.render_dirty_regions]: [false]
[dev.bootcomplete]: [1]
[dhcp.area.value]: [hblt.wotv]
[dhcp.area1.value]: [SCITVDHCP]
[dhcp.iptvstart.network]: [1]
[dhcp.option125]: [1]
[dhcp.option60.value]: [SCITV]
[dhcp.password]: []
[dhcp.retries]: [5]
[dhcp.timeout]: [5]
[dhcp.username]: []
[dhcp.vendorclassid]: []
[dhcp.vendorspecinfo]: []
[dhcp.waittime]: [30]
[dhcp.wlan0.85.result]: [failed]
[dhcp.wlan0.b.enable]: [false]
[dhcp.wlan0.ctc22]: [0]
[dhcp.wlan0.dns1]: [192.168.2.1]
[dhcp.wlan0.doublevlan]: [0]
[dhcp.wlan0.gateway]: [192.168.2.1]
[dhcp.wlan0.ipaddress]: [192.168.2.46]
[dhcp.wlan0.leasetime]: [86400]
[dhcp.wlan0.mask]: [255.255.255.0]
[dhcp.wlan0.password]: []
[dhcp.wlan0.result]: [ok]
[dhcp.wlan0.server]: [192.168.2.1]
[dhcp.wlan0.username]: []
[drm.client.enabled]: [false]
[drm.service.enabled]: [true]
[drm.widevine.debug]: [false]
[gsm.version.baseband]: [HiSTBAndroidV600R003C01SPC032]
[hibrowser.default.fullscreen]: [true]
[init.svc.adbd]: [running]
[init.svc.bigfish-setup]: [stopped]
[init.svc.bootanim]: [stopped]
[init.svc.console]: [running]
[init.svc.debuggerd]: [running]
[init.svc.display]: [running]
[init.svc.dlnaserver]: [running]
[init.svc.drm]: [running]
[init.svc.exitfastplay]: [stopped]
[init.svc.flash_recovery]: [stopped]
[init.svc.gpio-led]: [stopped]
[init.svc.healthd]: [running]
[init.svc.hiaoservice]: [running]
[init.svc.hikaraokeservice]: [running]
[init.svc.hipq]: [running]
[init.svc.hisysmanager]: [running]
[init.svc.installd]: [running]
[init.svc.ir_user]: [running]
[init.svc.keystore]: [running]
[init.svc.media]: [running]
[init.svc.netd]: [running]
[init.svc.netshared]: [running]
[init.svc.onekeycollect]: [stopped]
[init.svc.p2p_supplicant]: [running]
[init.svc.preinstall]: [stopped]
[init.svc.servicemanager]: [running]
[init.svc.softdetector]: [running]
[init.svc.surfaceflinger]: [running]
[init.svc.udhcpc_wlan0]: [running]
[init.svc.ueventd]: [running]
[init.svc.upgradeserver]: [running]
[init.svc.vold]: [running]
[init.svc.xiriservice]: [running]
[init.svc.zygote]: [running]
[media.hiplayer.md]: [0]
[multi.dev.select]: [1]
[net.bt.name]: [Android]
[net.change]: [net.dns1]
[net.dns1]: [192.168.2.1]
[net.hostname]: [android-a7131d44d8f1f7c7]
[net.qtaguid_enabled]: [1]
[net.tcp.buffersize.default]: [4096,87380,110208,4096,16384,110208]
[net.tcp.buffersize.edge]: [4093,26280,35040,4096,16384,35040]
[net.tcp.buffersize.evdo]: [4094,87380,262144,4096,16384,262144]
[net.tcp.buffersize.gprs]: [4092,8760,11680,4096,8760,11680]
[net.tcp.buffersize.hsdpa]: [4094,87380,262144,4096,16384,262144]
[net.tcp.buffersize.hspa]: [4094,87380,262144,4096,16384,262144]
[net.tcp.buffersize.hspap]: [4094,87380,1220608,4096,16384,1220608]
[net.tcp.buffersize.hsupa]: [4094,87380,262144,4096,16384,262144]
[net.tcp.buffersize.lte]: [524288,1048576,2097152,262144,524288,1048576]
[net.tcp.buffersize.umts]: [4094,87380,110208,4096,16384,110208]
[net.tcp.buffersize.wifi]: [524288,1048576,2097152,262144,524288,1048576]
[persist.ethernet.doublestack]: [false]
[persist.ethernet.vlan.area]: [none]
[persist.ethernet.vlan.enabled]: [false]
[persist.ethernet.vlanid]: [0]
[persist.ethernet.wifidisguise]: [false]
[persist.hdmi.suspend.enable]: [1]
[persist.hdmi.suspend.time]: [0]
[persist.iptv.startup_enable]: [1]
[persist.iptv.zte_nat_through]: [1]
[persist.karaoke.enable]: [true]
[persist.low_ram.wp.enable]: [false]
[persist.service.adb.enable]: [1]
[persist.service.bdroid.bdaddr]: [22:22:9f:70:18:f2]
[persist.suspend.mode]: [deep_restart]
[persist.sys.access.internal]: [false]
[persist.sys.activity.constss]: [/system/media/blank.png]
[persist.sys.adb.enable]: [1]
[persist.sys.audio.blueray]: [0]
[persist.sys.audio.hdmi.output]: [2]
[persist.sys.audio.spdif.output]: [3]
[persist.sys.audio.truehd]: [0]
[persist.sys.audio.volume]: [53]
[persist.sys.baseformat]: [0]
[persist.sys.bootanim.compeleted]: [false]
[persist.sys.bootanim.enable]: [true]
[persist.sys.bootanim.playmode]: [freeze]
[persist.sys.capgetfailflag]: [-1]
[persist.sys.cec.hardware]: [true]
[persist.sys.cec.status]: [false]
[persist.sys.cecsupport]: [true]
[persist.sys.colorspacesettype]: [-1]
[persist.sys.console.enable]: [1]
[persist.sys.ctc.errcover.fast]: [10]
[persist.sys.ctc.errcover.fisfrm]: [10]
[persist.sys.ctc.errcover.resume]: [10]
[persist.sys.ctc.errcover.seek]: [10]
[persist.sys.ctc.errcover.spfast]: [10]
[persist.sys.ctc.presynctimeout]: [0]
[persist.sys.ctc.quickoutput]: [1]
[persist.sys.cvbs.and.hdmi]: [false]
[persist.sys.dalvik.vm.lib]: [libdvm.so]
[persist.sys.display.adb]: [1]
[persist.sys.display.customize]: [1,1,50,50,50,50,4,4,4,4,2,2,0,]
[persist.sys.display.param]: [1,0,50,50,50,50,4,4,4,4,2,2,0,]
[persist.sys.doublenet]: [false]
[persist.sys.ethernet.status]: [eth0_on]
[persist.sys.fastplay.fullyplay]: [false]
[persist.sys.hdmi.cec]: [true]
[persist.sys.hdmi.edid0]: [506c0032000000002b1b4700000000000000000000000000000000000000000000000000000000000000000000]
[persist.sys.hdmi.edid1]: [0103804628783aca75a90000000000000000000000000000000000000000000000000000000000000000000000]
[persist.sys.hdmi.edid2]: [544598221f5054a54b000000001e000021515600452c58402d387118804880004b30010100001a680010000c03]
[persist.sys.hdmi.edid3]: [714081c081809500a9c06500000183070709231f131211040302019049f1250302a9010a202020202020202020]
[persist.sys.hdmi.edid4]: [b300d1c00101023a801820202000ff00000020200a43364d323354204c435400fc0000002020202020200a0014]
[persist.sys.hdmi.edid5]: [71382d40582c4500ba89641f4b3000fd0000001e000021]
[persist.sys.hdmicecsuspend.time]: [0]
[persist.sys.hdrmode]: [-1]
[persist.sys.hiplayer.rtspusetcp]: [false]
[persist.sys.hiplayer.vo.freeze]: [false]
[persist.sys.imeswitch.key]: [18]
[persist.sys.instructions.id]: [E4259D90040AA32294359681AC0F3D1D]
[persist.sys.laterscan.enable]: [false]
[persist.sys.optimalfmt.enable]: [1]
[persist.sys.optimalfmt.perfer]: [p50hz]
[persist.sys.player.avsync.min]: [500]
[persist.sys.player.buffer.seek]: [0]
[persist.sys.player.bufmaxsize]: [80]
[persist.sys.player.cache.high]: [5300]
[persist.sys.player.cache.low]: [200]
[persist.sys.player.cache.total]: [20000]
[persist.sys.player.cache.type]: [time]
[persist.sys.player.leftbuf.min]: [10]
[persist.sys.pqhdr.configmode]: [1]
[persist.sys.pqhdr.tmp]: [default,50,50,53,50,50,50,50,40,50,15,0,1,1]
[persist.sys.preload.fork]: [true]
[persist.sys.profiler_ms]: [0]
[persist.sys.resolution]: [1080]
[persist.sys.samba.status]: [true]
[persist.sys.screen_density]: [240]
[persist.sys.screencapture.key]: [0]
[persist.sys.screenorientation]: [landscape]
[persist.sys.softdetector.enable]: [false]
[persist.sys.swap.enable]: [1]
[persist.sys.timezone]: [Asia/Shanghai]
[persist.sys.tr069.log]: [4]
[persist.sys.tv.dpi]: [1920*1080]
[persist.sys.tv.name]: [TCL]
[persist.sys.tv.size]: [32]
[persist.sys.tv.type]: [TCL T32M6C
  ]
[persist.sys.ui.hw]: [true]
[persist.sys.usb.config]: [mtp,adb]
[persist.sys.video.adaptformat]: [false]
[persist.sys.video.cvrs]: [0]
[persist.sys.win.switch.black]: [true]
[persist.sys.zygote.optimize]: [false]
[persist.wifi.checkinternet]: [false]
[pq.procuct.tv.name]: [TCL12800]
[qcom.bluetooth.soc]: [rome]
[qemu.hw.mainkeys]: [0]
[ro.adb.secure]: [1]
[ro.allow.mock.location]: [1]
[ro.baseband]: [unknown]
[ro.board.platform]: [bigfish]
[ro.bootloader]: [unknown]
[ro.bootmode]: [unknown]
[ro.bt.bdaddr_path]: [/data/misc/bluetooth/bdaddr]
[ro.bt_init.enable]: [false]
[ro.build.characteristics]: [tablet]
[ro.build.date.utc]: [1543551973]
[ro.build.date]: [Fri Nov 30 12:26:13 CST 2018]
[ro.build.description]: [Hi3798MV310-eng 4.4.2 KOT49H 1.361158.00 test-keys]
[ro.build.display.id]: [Hi3798MV310-eng 4.4.2 KOT49H 1.361158.00 test-keys]
[ro.build.fingerprint]: [Fiberhome/Hi3798MV310/Hi3798MV310:4.4.2/KOT49H/1.361158.00:eng/test-keys]
[ro.build.hardware.id]: [Hi3798MV310]
[ro.build.host]: [STB02]
[ro.build.id]: [KOT49H]
[ro.build.product]: [Hi3798MV310]
[ro.build.tags]: [test-keys]
[ro.build.type]: [eng]
[ro.build.user]: [jenkins]
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [1.361158.00]
[ro.build.version.release]: [4.4.2]
[ro.build.version.sdk]: [19]
[ro.carrier]: [unknown]
[ro.com.android.dateformat]: [MM-dd-yyyy]
[ro.com.widevine.cachesize]: [16777216]
[ro.communication.ip]: []
[ro.communication.port]: []
[ro.config.alarm_alert]: [Alarm_Classic.ogg]
[ro.config.low_ram]: [false]
[ro.config.notification_sound]: [pixiedust.ogg]
[ro.config.ringtone]: [Ring_Synth_04.ogg]
[ro.config.tde_compose]: [true]
[ro.debuggable]: [1]
[ro.decode.cap.h264]: [4kp30]
[ro.decode.cap.h265]: [4kp60]
[ro.defaultStorage.enable]: [true]
[ro.deviceid]: []
[ro.dolby.dmacert.enable]: [false]
[ro.dolby.dvbcert.enable]: [false]
[ro.dolby.iptvcert.enable]: [false]
[ro.drm.tee]: [false]
[ro.encode.cap.h264]: [1080p30]
[ro.encode.cap.h265]: [1080p30]
[ro.factorytest]: [0]
[ro.fix.portconfilict]: [1]
[ro.fuse.support]: [false]
[ro.hardware]: [bigfish]
[ro.hwcursor.fb]: [/dev/graphics/fb2]
[ro.kernel.android.checkjni]: [false]
[ro.lockscreen.disable.default]: [true]
[ro.mac]: [88:23:8C:B7:DC:EE]
[ro.mediaScanner.enable]: [false]
[ro.nfc.port]: [I2C]
[ro.opengles.version]: [131072]
[ro.playready.tee]: [false]
[ro.pmqos.enable]: [true]
[ro.product.board]: [bigfish]
[ro.product.brand]: [Fiberhome]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.device]: [Hi3798MV310]
[ro.product.locale.language]: [zh]
[ro.product.locale.region]: [CN]
[ro.product.manufacturer]: [Fiberhome]
[ro.product.mem.size]: [1g]
[ro.product.model.hardware]: [HG680-AYERX-0B]
[ro.product.model]: [Vidaa TV]
[ro.product.name]: [Vidda TV]
[ro.product.operator]: [CMCC]
[ro.product.target]: [telecom]
[ro.revert.support]: [true]
[ro.revision]: [0]
[ro.runtime.firstboot]: [1634642351010]
[ro.secure]: [0]
[ro.serialno]: [0010059900E06800122088238CB7DCEE]
[ro.sf.lcd_density]: [160]
[ro.support.db]: [1]
[ro.sys.apkcontrol.mode]: [none]
[ro.tether.denied]: [false]
[ro.thirdparty.dhcp]: [false]
[ro.toastshow.enable]: [false]
[ro.total.flash]: [8G]
[ro.total.memsize]: [1G]
[ro.wifi.channels]: []
[service.adb.tcp.port]: [5555]
[service.bootanim.exit]: [0]
[service.hwc.skip.compose]: [false]
[service.media.hiplayer.output]: [sideband]
[service.media.playstatus]: [running]
[service.mountservice.reset]: [0]
[service.vold.status]: [Crashed]
[supolicy.loaded]: [1]
[sys.boot_completed]: [1]
[sys.insmod.ko]: [1]
[sys.internal.primary]: [true]
[sys.qb.reload]: [load_persist_props]
[sys.settings_global_version]: [2]
[sys.settings_system_version]: [1]
[sys.sysctl.extra_free_kbytes]: [24300]
[sys.usb.config]: [mtp,adb]
[sys.vold.emulated]: [mount]
[system_init.startsurfaceflinger]: [0]
[wifi.interface]: [wlan0]
[wlan.driver.status]: [ok]

**Comment by leandrotsampa** [comment]
Need UART open with I/O enabled and SDK for your SoC.
With this you can compile a kernel and try boot from UART.
