### ISSUE TITLE
Its possible to add LNB controler A8304 ? 

### ISSUE THREAD

**Issue by rebainoor** [leandrotsampa/hisilicon-kernel#2]
Its possible to add LNB controler A8304 ? what need to add it 
For MSP 
https://github.com/SiliconLabs/video_si21xx_superset/tree/master/SILABS_SUPERSET/SAT/LNB

**Comment by leandrotsampa** [comment]
> Its possible to add LNB controler A8304 ? what need to add it For MSP https://github.com/SiliconLabs/video_si21xx_superset/tree/master/SILABS_SUPERSET/SAT/LNB

You need change LNB Control in Frontend.
https://github.com/leandrotsampa/hisilicon-kernel/tree/atto-linux/drivers/msp/drv/frontend/lnbctrl
